cat website/template.html           >   index.html
cat website/index.html              >>  index.html
cat website/template.html           >   rules.html
cat website/rules.html              >>  rules.html
cat website/template.html           >   styles.html
cat website/styles.html             >>  styles.html
cat website/template.html           >   rulesets.html
cat website/rulesets.html           >>  rulesets.html
cat website/template.html           >   events.html
cat website/events.html             >>  events.html
cat website/template.html           >   resources.html
cat website/resources.html          >>  resources.html
cat website/template.html           >   commentators.html
cat website/commentators.html       >>  commentators.html
cat website/template.html           >   random.html
cat website/random.html             >>  random.html
cat website/template.html           >   teams.html
cat website/teams.html              >>  teams.html
cat website/template.html           >   teams2.html
cat website/teams2.html             >>  teams2.html
cat website/template.html           >   teamsfancy.html
cat website/teamsfancy.html         >>  teamsfancy.html
cat website/template.html           >   tournaments.html
cat website/tournaments.html        >>  tournaments.html
cat website/template.html           >   thoughts.html
cat website/thoughts.html           >>  thoughts.html
cat website/template.html           >   thoughts/throws.html
cat website/thoughts/throws.html    >>  thoughts/throws.html
cat website/template.html           >   thoughts/dice.html
cat website/thoughts/dice.html      >>  thoughts/dice.html
cat website/template.html           >   thoughts/advantage.html
cat website/thoughts/advantage.html >>  thoughts/advantage.html
cat website/template.html           >   thoughts/lumoki.html
cat website/thoughts/lumoki.html    >>  thoughts/lumoki.html
