cat website/template.txt            >   index.html
cat website/index.txt               >>  index.html
cat website/template.txt            >   rules.html
cat website/rules.txt               >>  rules.html
cat website/template.txt            >   styles.html
cat website/styles.txt              >>  styles.html
cat website/template.txt            >   rulesets.html
cat website/rulesets.txt            >>  rulesets.html
cat website/template.txt            >   events.html
cat website/events.txt              >>  events.html
cat website/template.txt            >   resources.html
cat website/resources.txt           >>  resources.html
cat website/template.txt            >   commentators.html
cat website/commentators.txt        >>  commentators.html
cat website/template.txt            >   random.html
cat website/random.txt              >>  random.html
cat website/template.txt            >   teams.html
cat website/teams.txt               >>  teams.html
cat website/template.txt            >   teams2.html
cat website/teams2.txt              >>  teams2.html
cat website/template.txt            >   tournaments.html
cat website/tournaments.txt         >>  tournaments.html
cat website/template.txt            >   thoughts/throws.html
cat website/thoughts/throws.txt     >>  thoughts/throws.html
cat website/template.txt            >   thoughts.html
cat website/thoughts.txt            >>  thoughts.html
cat website/template.txt            >   thoughts/dice.html
cat website/thoughts/dice.txt       >>  thoughts/dice.html
cat website/template.txt            >   thoughts/advantage.html
cat website/thoughts/advantage.txt  >>  thoughts/advantage.html
